### ISSUE TITLE
Improve user experience

### ISSUE THREAD

**Issue by Sevitas** [kontent-ai/model-generator-net#154]
### Motivation

Improves user experience while running generation tool. 
- Clears up the confusion between models compatibility and used SDK.
- Notifies user of using invalid parameters

#### 1. Improve logging of intended model SDK with version
actual message:
```
16 content type models were successfully created.
CustomTypeProvider class was successfully created. 
```
proposed message:
```
16 content type models were successfully created.
CustomTypeProvider class was successfully created. 
Models were generated for Delivery/Management SDK version x.x.x
```

#### 2. Introduce check for invalid parameters instead of ignoring them
We have 2 options for reacting to invalid character:
  a. Fail with an error message (breaking change)
  b. Display error message and continue with execution if possible

### Additional context
Discovered while [https://github.com/kontent-ai/management-sdk-net/issues/183](https://github.com/kontent-ai/management-sdk-net/issues/183)

**Comment by Simply007** [comment]
I would say warning/error message and continue with execution if possible is better.
