### ISSUE TITLE
Support for DateTime element timezones

### ISSUE THREAD

**Issue by Sevitas** [kontent-ai/model-generator-net#172]
### Motivation

As part of [#356](https://github.com/kontent-ai/delivery-sdk-net/pull/357) we added new `DateTimeContentConverter` to Delivery .NET SDK to have a possibility to convert DateTimeElement to custom `DateTimeContent` model, which has the following interface:

```
public interface IDateTimeContent
{
    public DateTime? Value { get; }
    public string DisplayTimezone { get; }
}
```
At the same time, we kept the possibility to convert DateTimeElement to system `DateTime?` type the same as it worked before.

It's needed to extend the model generator's functionality to let customers choose, whether they want to convert DateTimeElement to simple `DateTime?` value (previous behavior) or to custom `IDateTimeContent` model.

### Proposed solution

It seems reasonable to use similar approach as for RichTextElement converting. Model generator creates a property of `string` or custom `IRichTextContent` model depending on `--structuredmodel <True|False>` parameter value.
As we discussed on grooming, we can change type of `structuredmodel` property from current `bool` to `string`, so that it will contain a list of element types, for which custom type will be generated. Currently, there will be two possible elements, for with structured model could be generated:

- RichTextElement
- DateTimeElement

So, possible `structuredmodel` property format could be
`--structuredmodel richtext|datetime`

### Additional context

Add any other context, screenshots, or reference links about the feature request here.

**Comment by Simply007** [comment]
Add information about this feature to https://github.com/kontent-ai/delivery-sdk-net/blob/master/docs/customization-and-extensibility/rich-text/structured-rich-text-rendering.md

**Comment by dzmitryk-kontent-ai** [comment]
Also, please, update information about this feature to https://github.com/kontent-ai/delivery-sdk-net/blob/master/docs/customization-and-extensibility/strong-types-explained/code-generator.md
