### ISSUE TITLE
Skip prefixes for the field names generated from snippet

### ISSUE THREAD

**Issue by AntonDriemin** [kontent-ai/model-generator-net#182]
### Motivation

The name prefix will always be present for the properties generated for a model with the snippet.
For example, I have a snippet with the codename "Address" with fields "Country", "City"
My generated model will be
Address_Country
Address_City
so, all my properties will be with the prefixes if they are generated from the snippet.
It is not ok for the common coding conventions adopted by most organizations. And not convenient.

### Proposed solution

Implement an optional argument that will let us generate properties without Snipped codename as a prefix.

### Additional context

![image](https://user-images.githubusercontent.com/7961622/235089944-b87282e3-b216-4e56-97b7-680d71e25ba5.png)

**Comment by Sevitas** [comment]
Hi @AntonDriemin,
we have discussed this a bit further. We do not think it is a good idea to generate properties without a snippet prefix. The reasoning behind this is that it might generate invalid models. 

Consider scenario:
ContentType:
![image](https://user-images.githubusercontent.com/9439623/236183051-f71399d9-bee4-40f0-8359-6e621272eabe.png)
ContentTypeSnippet:
![image](https://user-images.githubusercontent.com/9439623/236183237-30f7fe41-d7f1-4b70-856e-5edb5e28d201.png)

 This would result in an invalid model and also a duplicate property error.
![image](https://user-images.githubusercontent.com/9439623/236183686-3ae7c0a4-9bfc-4dfe-98aa-4a62b510fe6f.png)


As an alternative you might use:
- [customization and extensibility](https://github.com/kontent-ai/delivery-sdk-net/blob/master/docs/customization-and-extensibility/customization-techniques.md#via-interfaces)

@AntonDriemin do you think this can work for you?

**Comment by Sevitas** [comment]
This issue was closed due to inactivity. If you would like to elaborate on it a bit further, feel free to reopen the issue.

**Comment by Sevitas** [comment]
Hi @AntonDriemin, thank you for explaining the use case. We need to consider your request a bit further, so I will get back you with the response. Have you considered using [customization and extensibility](https://github.com/kontent-ai/delivery-sdk-net/blob/master/docs/customization-and-extensibility/customization-techniques.md#via-interfaces) as I have suggested in the previous comment?

**Comment by AntonDriemin** [comment]
> Hi @AntonDriemin, thank you for explaining the use case. We need to consider your request a bit further, so I will get back you with the response. Have you considered using [customization and extensibility](https://github.com/kontent-ai/delivery-sdk-net/blob/master/docs/customization-and-extensibility/customization-techniques.md#via-interfaces) as I have suggested in the previous comment?

Yes, I'm using interfaces for partial classes to ensure consistency of the components in a way:
`    public partial class Eventspage : IKontentPage, IPreviewPage
    {
    }
`
Thank you.

**Comment by Sevitas** [comment]
Hi @AntonDriemin,
We have considered your scenario but implementing the requested feature is not a good idea. On the other hand, there is a possible workaround for your use case.

 You can use [Customizing the property matching](https://github.com/kontent-ai/delivery-sdk-net/blob/master/docs/customization-and-extensibility/strongly-typed-models.md#customizing-the-property-matching) and implementing your own _IPropertyMapper_. As an inspiration, you can use [PropertyMapper](https://github.com/kontent-ai/delivery-sdk-net/blob/49fde38ff5f20e793551d9d13534ec63f525470d/Kontent.Ai.Delivery/ContentItems/PropertyMapper.cs). To ensure your models have the expected property name you need to generate your models with a base class option [-b](https://github.com/kontent-ai/model-generator-net#delivery-api-parameters). In the generate base class file you can create your properties. 

**_Note:_** be aware, that the base class properties will be generated for all of your content types. _If you would like to prevent this you can do that by editing the **{BaseClassName}Extender.cs file**, but be aware of the fact, that after regenerating your models you will lose all of your changes done in **{BaseClassName}Extender.cs** file._

I can provide you with an example:
CustomPropertyMapper.cs:
```csharp
using System.Reflection;
using Kontent.Ai.Delivery.Abstractions;

namespace KontentAiModels
{
    public class CustomPropertyMapper : IPropertyMapper
    {
        public bool IsMatch(PropertyInfo modelProperty, string fieldName, string contentType)
        {
            return modelProperty.Name.ToLower() == fieldName || (fieldName.EndsWith(modelProperty.Name.ToLower()) && fieldName.StartsWith("snippet"));
        }
    }
}
```

Content type model files:
```csharp
using Kontent.Ai.Delivery.Abstractions;

namespace KontentAiModels
{
    public partial class ContentType1
    {
        public const string Codename = "content_type_1";
        public const string NumberCodename = "number";
        public const string Snippet1TextCodename = "snippet_1__text";

        public decimal? Number { get; set; }
        public string Snippet1Text { get; set; }
        public IContentItemSystemAttributes System { get; set; }
    }
}
```

```csharp
using Kontent.Ai.Delivery.Abstractions;

namespace KontentAiModels
{
    public partial class ContentType2
    {
        public const string Codename = "content_type_1";
        public const string NumberCodename = "number";
        public const string Snippet1TextCodename = "snippet_1__text";

        public decimal? Number { get; set; }
        public string Snippet1Text { get; set; }
        public IContentItemSystemAttributes System { get; set; }
    }
}
```

Base class file: SnippetPropertyContainer.cs
```csharp
namespace KontentAiModels
{
    public partial class SnippetPropertyContainer
    {
        public string Text { get; set; }
    }
}
```

Base class extender file: SnippetPropertyContainerExtender.cs
```csharp
using System;
using Kontent.Ai.Delivery.Abstractions;

namespace KontentAiModels
{
    // These classes extend the generated models to all inherit from the common basetype SnippetPropertyContainer.
    public partial class ContentType1 : SnippetPropertyContainer
    {
    }

    public partial class ContentType2 : SnippetPropertyContainer
    {
    }
}
```

Usage of a delivery client:
```csharp
public class Program
{
    public static async Task<int> Main(string[] args)
    {
        var deliveryClient = DeliveryClientBuilder
            .WithProjectId("837a062d-bb42-0079-a849-9b31bf7a9fca")
            .WithTypeProvider(new CustomTypeProvider())
            .WithPropertyMapper(new CustomPropertyMapper())
            .Build();

        var items = await deliveryClient.GetItemsAsync<ContentType1>();
    }
}

```

**Comment by Sevitas** [comment]
Hi @AntonDriemin, 
I'd like to confirm that the proposed solution is working for you. If you do not have any other questions we would like to close the issue.

**Comment by AntonDriemin** [comment]
Hi @Sevitas it looks like I don't have another option except this one. Let's consider this as done.
Thank you for your effort!
