### ISSUE TITLE
Management API: Guidelines element prevents generating the rest of snippet properties.

### ISSUE THREAD

**Issue by rebelzach** [kontent-ai/model-generator-net#185]
### Brief bug description

Guidelines element prevents generating the rest of snippet properties.

### Repro steps

1. Add a snippet with a Guidelines element and a subsequent Text element
2. Add the snippet to a type
3. Run the generator for the Management API models.
4. The model does not contain a property for the Text element. 

### Expected behavior

The Guidelines element property to be absent and the Text element property to be included.

### Test environment

 - Platform/OS: Windows net6
 - Version 8.3.1

**Comment by Sevitas** [comment]
Hi @rebelzach,
thanks for submitting the issue. I have prepared a fix in #186.

**Comment by rebelzach** [comment]
Appreciate the quick fix. Looking forward to its release. 🚀

**Comment by Sevitas** [comment]
Hi @rebelzach, the fix should be in https://github.com/kontent-ai/model-generator-net/releases/tag/8.3.2. Closing for now.
